_BASE_: ../Base-SBS.yml

DATASETS:
  NAMES: ("DogReID",)
  TESTS: ("DogReID",)

OUTPUT_DIR: logs/DogReID/sbs_R50_IBN

INPUT:
  SIZE_TRAIN: [ 384, 384 ]
  SIZE_TEST: [ 384, 384 ]

DATALOADER:
  NUM_INSTANCE: 4

MODEL:
  BACKBONE:
    DEPTH: 50x
    WITH_IBN: True

SOLVER:
  MAX_EPOCH: 120
  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 20
